//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Show_Presentation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura
    {
        public int Id { get; set; }
        public Nullable<int> Nombre_producto { get; set; }
        public Nullable<int> Categoria_Cliente { get; set; }
        public Nullable<int> Monto_total { get; set; }
        public Nullable<int> Catidad { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual inventario inventario { get; set; }
        public virtual productos productos { get; set; }
    }
}
